---
title: "CV"
author: "J TED Carter"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    number_sections: false
    toc: yes
    always_allow_html: true
    
    
bibliography:
- R-packages.bib
- aRticles.bib

csl: ecology.csl
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE,
                      message=FALSE,
                      warning=FALSE)

library(papaja)
#library(pdflatex)

papaja::r_refs(file="CV.bib")

options(knitr.kable.NA="")

```

```{r letter, echo=FALSE}
# Cover Letter


```

\newpage

---
Contact Information:
  J. pTED Carter
    (FKA; J.R. Hillert II)

Office: 
236 Moose Vlg. 
  31-2
Cullowhee, NC 28723
---

---
Email(s):

~jtedcarter@gmail.com (personal)

~nottedy@gmail.com (commissions)

~info@nottedysorange.co
---

---
Descriptive terms...
  [Scientist](nottedysorangeco.net)
  [Artist](https://www.instagram.com/nottedysorangeco/)
  [Enigma] 
      [sm.Bizz](nottedysorange.co) 
      [personal.Instagram](https://www.instagram.com/_nottedy/)

---

\newpage

```{r cover letter, echo=FALSE}
# Cover Letter


```

\newpage

```{r reumes, echo=FALSE}
# Resumes

### Professional



### Academic



### Certifications



```

\newpage

```{r refs, echo=FALSE}
# References

### Professional



### Academic



### Certifications



```

\newpage

```{bits, echo=FALSE}
# Other

#### [Monthly Newsletter](broken link...)

#### Hobbies

```